### ISSUE TITLE
服务器报错

### ISSUE THREAD

**Issue by junxiesky** [wode490390/Nukkit#30]
22:00:55 [ERROR] Throwing
java.lang.ArrayIndexOutOfBoundsException: 2
        at cn.nukkit.inventory.transaction.CraftingTransaction.setInput(CraftingTransaction.java:53) ~[nukkit.jar:?]
        at cn.nukkit.inventory.transaction.action.CraftingTransferMaterialAction.onAddToTransaction(CraftingTransferMaterialAction.java:25) ~[nukkit.jar:?]
        at cn.nukkit.inventory.transaction.InventoryTransaction.addAction(InventoryTransaction.java:68) ~[nukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2888) ~[nukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
        at cn.nukkit.network.Network.processPackets(Network.java:185) ~[nukkit.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:167) [nukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2072) [nukkit.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:76) [nukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1123) [nukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:880) [nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:565) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
嘿嘿嘿

**Comment by Anders233** [comment]
删服保平安![滑稽](http://img.9553.com/uploadfile/2016/0330/20160330063414501.jpg)

**Comment by 3zeroed** [comment]
删服保平安![滑稽](http://img.9553.com/uploadfile/2016/0330/20160330063414501.jpg)

**Comment by junxiesky** [comment]
过分了

**Comment by 3zeroed** [comment]
> 过分了

没有安装插件吗

**Comment by junxiesky** [comment]
安装了，但是是合成物品出的

**Comment by junxiesky** [comment]
合成物品出的报错

**Comment by 3zeroed** [comment]
> 合成物品出的报错

有没有卸载全部插件试过呢

**Comment by junxiesky** [comment]
@Anders233 没有

**Comment by 3zeroed** [comment]
> 合成物品出的报错

有没有卸载全部插件试过呢

> @Anders233 没有

试试吧

**Comment by junxiesky** [comment]
@Anders233 问题是我不知道这个是怎么触发的，我的玩家触发的

**Comment by wode490390** [comment]
Duplicate of https://github.com/NukkitX/Nukkit/issues/822
